@startuml

' === Клас базової кави ===
class Coffee {
  +get_description()
  +cost()
}

' === Конкретні напої ===
class Espresso
class Latte
class Cappuccino

Espresso -|> Coffee
Latte -|> Coffee
Cappuccino -|> Coffee

' === Декоратори ===
class IngredientDecorator {
  -coffee: Coffee
  +get_description()
  +cost()
}

class Milk
class Chocolate
class Syrup

Milk -|> IngredientDecorator
Chocolate -|> IngredientDecorator
Syrup -|> IngredientDecorator
IngredientDecorator --> Coffee


class CoffeeFactory {
  +create_coffee(type_name)
}

CoffeeFactory ..> Espresso : creates
CoffeeFactory ..> Latte : creates
CoffeeFactory ..> Cappuccino : creates


class Order {
  -status
  -observers
  +add_observer()
  +remove_observer()
  +set_status()
  +notify_observers()
}

class OrderObserver {
  +update(status)
}

class Customer {
  +update(status)
}

Customer -|> OrderObserver
Order --> OrderObserver

@enduml
